"""qd init — zero-config bootstrap: detect the fleet, generate defaults, never clobber.

Doctrine:
- additive only: config.yaml is created only if missing; schedules.yaml is MERGED —
  entries the user touched are never overwritten, discovered jobs are appended;
- auto-tighten is allowed, auto-loosen is not: defaults start conservative (fail-closed
  watchdog, redaction on); anything that would widen behavior is proposed, not applied;
- plists are never touched here — adoption stays behind `qd adopt ... --apply`.
"""

from pathlib import Path
from typing import Any

import yaml

from quarterdeck.adopt import scan

DEFAULT_CONFIG = """\
# Quarterdeck config (created by `qd init` — safe to edit, init never overwrites)
# paperclip:
#   api_base: http://127.0.0.1:3100
#   company_id: <set after Paperclip install>
# ledger_dir: ~/.local/state/quarterdeck/ledger
# redact: true
# capture_log_tail: true
"""


def default_grace(interval: int) -> int:
    """Conservative default; tightened later from observed run durations, never loosened
    automatically."""
    return max(300, interval // 5)


def generate_schedules(
    entries: list[dict[str, Any]], existing: dict[str, Any] | None
) -> tuple[dict[str, Any], dict[str, int]]:
    jobs: dict[str, dict[str, Any]] = {
        j["job"]: j for j in (existing or {}).get("jobs", []) if "job" in j
    }
    stats = {"discovered": 0, "added": 0, "kept": len(jobs), "calendar_unsupported": 0}
    for e in entries:
        if "error" in e or "job" not in e:
            continue
        stats["discovered"] += 1
        if e["job"] in jobs:  # user's entry wins, always
            continue
        entry: dict[str, Any] = {"job": e["job"], "source": e["label"]}
        if "expected_interval_seconds" in e:
            entry["expected_interval_seconds"] = e["expected_interval_seconds"]
            entry["grace_seconds"] = default_grace(e["expected_interval_seconds"])
        else:
            # No interval => watchdog reports it as unsupported (fail-closed, visible),
            # rather than silently dropping coverage.
            entry["note"] = f"calendar schedule {e.get('calendar')} — croniter support pending"
            stats["calendar_unsupported"] += 1
        jobs[e["job"]] = entry
        stats["added"] += 1
    return {"jobs": list(jobs.values())}, stats


def init_workspace(
    config_dir: Path, launchagents_dir: Path, *, crontab_text: str = ""
) -> dict[str, Any]:
    summary: dict[str, Any] = {"created": [], "merged": [], "stats": {}}
    config_dir.mkdir(parents=True, exist_ok=True)
    config_dir.chmod(0o700)

    config_yaml = config_dir / "config.yaml"
    if not config_yaml.exists():
        config_yaml.write_text(DEFAULT_CONFIG)
        summary["created"].append(str(config_yaml))

    entries = scan(launchagents_dir) if launchagents_dir.exists() else []
    schedules_yaml = config_dir / "schedules.yaml"
    existing = (
        yaml.safe_load(schedules_yaml.read_text()) if schedules_yaml.exists() else None
    )
    schedules, stats = generate_schedules(entries, existing)
    summary["stats"] = stats
    if schedules["jobs"]:
        schedules_yaml.write_text(
            "# Generated by `qd init` — merged, your edits are preserved on re-run\n"
            + yaml.safe_dump(schedules, allow_unicode=True, sort_keys=False)
        )
        (summary["merged"] if existing else summary["created"]).append(str(schedules_yaml))
    return summary
